Repository DEFRA/prsd-iws, pull requests merged in 2019-03, with the labels that each got.

#871 Producer report - input screen
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/Reports/Producer/ProducerReportDates.cs
  src/EA.Iws.Core/Reports/Producer/ProducerReportTextFields.cs
  src/EA.Iws.Core/Reports/TextFieldOperator.cs
  src/EA.Iws.Web/App_Start/BundleConfig.cs
  src/EA.Iws.Web/Areas/Admin/Views/Menu/_ReportingLinks.cshtml
  src/EA.Iws.Web/Areas/Reports/Controllers/ProducerController.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Producer/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/Producer/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/Producer/ProducerResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/Producer/ProducerResources.resx
  src/EA.Iws.Web/EA.Iws.Web.csproj
  src/EA.Iws.Web/Scripts/report-input-parameters.js
  src/EA.Iws.Web/ViewModels/Shared/ReportInputParametersResources.Designer.cs
  src/EA.Iws.Web/ViewModels/Shared/ReportInputParametersResources.resx
  src/EA.Iws.Web/ViewModels/Shared/ReportInputParametersViewModel.cs
  src/EA.Iws.Web/ViewModels/Shared/RequiredDateInputResources.Designer.cs
  src/EA.Iws.Web/ViewModels/Shared/RequiredDateInputResources.resx
  src/EA.Iws.Web/ViewModels/Shared/RequiredDateInputViewModel.cs
  src/EA.Iws.Web/Views/Shared/EditorTemplates/ReportInputParametersViewModel.cshtml
  src/EA.Iws.Web/Views/Shared/EditorTemplates/RequiredDateInputViewModel.cshtml
Labels: reporting

#863 Feature/internal shipment notification add comment
  src/EA.Iws.DataAccess/EA.Iws.DataAccess.csproj
  src/EA.Iws.DataAccess/ImportNotificationContext.cs
  src/EA.Iws.DataAccess/IwsContext.cs
  src/EA.Iws.DataAccess/Mappings/Exports/NotificationCommentMapping.cs
  src/EA.Iws.DataAccess/Mappings/Imports/ImportNotificationCommentMapping.cs
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationCommentRepository.cs
  src/EA.Iws.DataAccess/Repositories/NotificationCommentRepository.cs
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190228-1147-AddExpoirtNotificationCommentsTable.sql
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190228-1147-AddImportNotificationCommentsTable.sql
  src/EA.Iws.Domain/EA.Iws.Domain.csproj
  src/EA.Iws.Domain/ImportNotificationAssessment/IImportNotificationCommentRepository.cs
  src/EA.Iws.Domain/ImportNotificationAssessment/ImportNotificationComment.cs
  src/EA.Iws.Domain/NotificationAssessment/INotificationCommentRepository.cs
  src/EA.Iws.Domain/NotificationAssessment/NotificationComment.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/AddImportNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/AddNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/AddImportNotificationCommentHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/AddNotificationCommentHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/ImportNotificationAssessment/AddImportNotificationComment.cs
  src/EA.Iws.Requests/NotificationAssessment/AddNotificationComment.cs
  src/EA.Iws.Web/Areas/Admin/Views/Menu/_ExportNavigation.cshtml
  src/EA.Iws.Web/Areas/Admin/Views/Menu/_ImportNavigation.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/AddCommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/_Layout.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/AddCommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/EA.Iws.Web.csproj
Labels: shipment-notification-comments

#874 Feature/internal commments delete
  src/EA.Iws.Core/InternalComments/InternalComment.cs
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationCommentRepository.cs
  src/EA.Iws.DataAccess/Repositories/NotificationCommentRepository.cs
  src/EA.Iws.Domain/ImportNotificationAssessment/IImportNotificationCommentRepository.cs
  src/EA.Iws.Domain/NotificationAssessment/INotificationCommentRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/DeleteImportNotificationCommentHandlerTest.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/DeleteNotificationCommentHandlerTests.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/DeleteImportNotificationCommentHandler.cs
  src/EA.Iws.RequestHandlers/Mappings/ImportNotificationAssessment/ImportNotificationCommentMap.cs
  src/EA.Iws.RequestHandlers/Mappings/NotificationAssessment/NotificationCommentMap.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/DeleteNotificationCommentHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/ImportNotificationAssessment/DeleteImportNotificationComment.cs
  src/EA.Iws.Requests/ImportNotificationAssessment/DeleteNotificationComment.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/DeleteCommentViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Delete.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/DeleteCommentViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Delete.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/_Layout.cshtml
  src/EA.Iws.Web/EA.Iws.Web.csproj
Labels: shipment-notification-comments

#876 Producer report generation
  src/EA.Iws.Core/Admin/Reports/ProducerData.cs
  src/EA.Iws.Core/Authorization/Permissions/ReportingPermissions.cs
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/Reports/Producer/ProducerReportTextFields.cs
  src/EA.Iws.Core/Reports/TextFilterHelper.cs
  src/EA.Iws.DataAccess/Repositories/ProducerRepository.cs
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Everytime/02-Views/0027-Reports-Producers.sql
  src/EA.Iws.Domain/NotificationApplication/IProducerRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Admin/Reports/GetProducerReportHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers/Admin/Reports/GetProducerReportHandler.cs
  src/EA.Iws.RequestHandlers/Authorization/InMemoryAuthorizationManager.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.Requests/Admin/Reports/GetProducerReport.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.TestHelpers/DomainFakes/TestableInternalUser.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ProducerController.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Producer/IndexViewModel.cs
Labels: reporting

#877 Shipments report - input, generation & formatting
  src/EA.Iws.Core/Admin/Reports/ShipmentData.cs
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/Reports/ShipmentReportTextFields.cs
  src/EA.Iws.Core/Reports/ShipmentsReportDates.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ShipmentsRepository.cs
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Everytime/02-Views/0026-Reports-Shipments.sql
  src/EA.Iws.Database/scripts/Everytime/03-StoredProcedures/0008-uspUpdateReportCache.sql
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190304-1730-AlterReportShipmentsTable.sql
  src/EA.Iws.Domain/Reports/IShipmentsRepository.cs
  src/EA.Iws.RequestHandlers/Admin/Reports/GetShipmentsReportHandler.cs
  src/EA.Iws.RequestHandlers/Mappings/Reports/ShipmentMap.cs
  src/EA.Iws.Requests/Admin/Reports/GetShipmentsReport.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ProducerController.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ShipmentsController.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Shipments/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/Shipments/Index.cshtml
  src/EA.Iws.Web/Infrastructure/xlsxActionResult.cs
Labels: reporting

#878 Added filtering by date and shipment number to both import and export…
  src/EA.Iws.Core/ImportNotificationAssessment/ImportNotificationCommentsData.cs
  src/EA.Iws.Core/NotificationAssessment/NotificationCommentData.cs
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationCommentRepository.cs
  src/EA.Iws.DataAccess/Repositories/NotificationCommentRepository.cs
  src/EA.Iws.Domain/ImportNotificationAssessment/IImportNotificationCommentRepository.cs
  src/EA.Iws.Domain/NotificationAssessment/INotificationCommentRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/GetImportNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/GetNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/GetImportNotificationCommentsHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/GetNotificationCommentsHandler.cs
  src/EA.Iws.Requests/ImportNotificationAssessment/GetImportNotificationComments.cs
  src/EA.Iws.Requests/NotificationAssessment/GetNotificationComments.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/DeleteCommentViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/DeleteCommentViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.resx
Labels: shipment-notification-comments

#880 Producer Report Update
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/Reports/ProducerReportDates.cs
  src/EA.Iws.Core/Reports/ProducerReportTextFields.cs
  src/EA.Iws.DataAccess/EA.Iws.DataAccess.csproj
  src/EA.Iws.DataAccess/Repositories/ProducerRepository.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ProducerRepository.cs
  src/EA.Iws.Domain/EA.Iws.Domain.csproj
  src/EA.Iws.Domain/NotificationApplication/IProducerRepository.cs
  src/EA.Iws.Domain/Reports/IProducerRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Admin/Reports/GetProducerReportHandlerTests.cs
  src/EA.Iws.RequestHandlers/Admin/Reports/GetProducerReportHandler.cs
  src/EA.Iws.Requests/Admin/Reports/GetProducerReport.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ProducerController.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Producer/IndexViewModel.cs
Labels: reporting

#881 Report input
  src/EA.Iws.DataAccess/Repositories/Reports/ProducerRepository.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ShipmentsRepository.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ProducerController.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ShipmentsController.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Producer/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Shipments/IndexViewModel.cs
  src/EA.Iws.Web/ViewModels/Shared/ReportInputParametersViewModel.cs
Labels: reporting

#882 Update size of site of export name column for shipments report.
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190304-1730-AlterReportShipmentsTable.sql
Labels: reporting

#888 Fix search for import notification to remove spaces.
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationSearchRepository.cs
Labels: bug

#889 Get latest FG. Update Order
  src/EA.Iws.Core/Reports/TextFieldOperator.cs
  src/EA.Iws.Database/scripts/Everytime/02-Views/0022-Reports-FreedomOfInformation.sql
Labels: reporting

#890 Minor text updates on the producer report.
  src/EA.Iws.Core/Admin/Reports/ProducerData.cs
  src/EA.Iws.Web/Areas/Reports/Views/Producer/ProducerResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/Producer/ProducerResources.resx
Labels: reporting

#891 Feature/customs office guidance
  src/EA.Iws.Web/Areas/NotificationApplication/Views/EntryCustomsOffice/Index.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/EntryCustomsOffice/_EntryCustomsOfficeGuidance.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/ExitCustomsOffice/Index.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/ExitCustomsOffice/_ExitCustomsOfficeGuidance.cshtml
  src/EA.Iws.Web/EA.Iws.Web.csproj
Labels: brexit

#892 Update text on facility for import notification.
  src/EA.Iws.Web/Areas/ImportNotification/Views/Facility/Edit.cshtml
Labels: address-book-imports

#894 Feature/internal comments paging
  src/EA.Iws.Core/ImportNotificationAssessment/ImportNotificationCommentsData.cs
  src/EA.Iws.Core/NotificationAssessment/NotificationCommentData.cs
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationCommentRepository.cs
  src/EA.Iws.DataAccess/Repositories/NotificationCommentRepository.cs
  src/EA.Iws.Domain/ImportNotificationAssessment/IImportNotificationCommentRepository.cs
  src/EA.Iws.Domain/NotificationAssessment/INotificationCommentRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/GetImportNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/GetNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/GetImportNotificationCommentsHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/GetNotificationCommentsHandler.cs
  src/EA.Iws.Requests/ImportNotificationAssessment/GetImportNotificationComments.cs
  src/EA.Iws.Requests/NotificationAssessment/GetNotificationComments.cs
  src/EA.Iws.Web/Areas/Admin/Views/Menu/ExportNavigationResources.Designer.cs
  src/EA.Iws.Web/Areas/Admin/Views/Menu/ExportNavigationResources.resx
  src/EA.Iws.Web/Areas/Admin/Views/Menu/ImportNavigationResources.Designer.cs
  src/EA.Iws.Web/Areas/Admin/Views/Menu/ImportNavigationResources.resx
  src/EA.Iws.Web/Areas/Admin/Views/Menu/_ImportNavigation.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/AddCommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Delete.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/IndexResources.resx
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/AddCommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Add.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Delete.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/IndexResources.resx
Labels: shipment-notification-comments

#895 Report input parameters view all
  src/EA.Iws.Web/Views/Shared/EditorTemplates/ReportInputParametersViewModel.cshtml
Labels: reporting

#896 Only use like operator for ewc and y codes.
  src/EA.Iws.DataAccess/Repositories/Reports/ProducerRepository.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ShipmentsRepository.cs
Labels: reporting

#897 Spelling corrections. Addition of column.
  src/EA.Iws.Core/Reports/FOI/FOIReportTextFields.cs
  src/EA.Iws.DataAccess/Repositories/Reports/FreedomOfInformationRepository.cs
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Everytime/02-Views/0022-Reports-FreedomOfInformation.sql
  src/EA.Iws.Database/scripts/Everytime/03-StoredProcedures/0008-uspUpdateReportCache.sql
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190308-1620-alter-foi-report-table2.sql
Labels: reporting

#898 Report amendments
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Finance/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/ExportStats/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/Finance/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/Finance/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/Finance/IndexResources.resx
  src/EA.Iws.Web/ViewModels/Shared/ReportInputParametersViewModel.cs
  src/EA.Iws.Web/ViewModels/Shared/RequiredDateInputViewModel.cs
Labels: reporting

#899 Update import stats report.
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/ImportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/ImportStats/Index.cshtml
Labels: reporting

#901 Return Ewc, Y codes and Facility on each row to fix issue with queries.
  src/EA.Iws.DataAccess/Repositories/Reports/ProducerRepository.cs
  src/EA.Iws.Database/scripts/Everytime/02-Views/0027-Reports-Producers.sql
Labels: reporting

#900 Hotfix/auto tab date
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/EA.Iws.Web.csproj
  src/EA.Iws.Web/ViewModels/Shared/DateEntryViewModel.cs
  src/EA.Iws.Web/Views/Shared/EditorTemplates/DateEntryViewModel.cshtml
Labels: shipment-notification-comments

#902 Return not applicable for waste codes when inidicated.
  src/EA.Iws.Database/scripts/Everytime/02-Views/0027-Reports-Producers.sql
Labels: reporting

#903 Add validation message for telephone prefix.
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModel.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.Designer.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.resx
  src/EA.Iws.Web/Areas/ImportNotification/Views/Shared/EditorTemplates/ContactViewModel.cshtml
Labels: address-book-imports

#904 Fix incorrect id on the join for producer report.
  src/EA.Iws.Database/scripts/Everytime/02-Views/0027-Reports-Producers.sql
Labels: reporting

#907 Added name filter
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/ImportNotificationAssessment/ImportNotificationCommentsUsersData.cs
  src/EA.Iws.Core/NotificationAssessment/NotificationCommentsUsersData.cs
  src/EA.Iws.DataAccess/Repositories/Imports/ImportNotificationCommentRepository.cs
  src/EA.Iws.DataAccess/Repositories/NotificationCommentRepository.cs
  src/EA.Iws.Domain/ImportNotificationAssessment/IImportNotificationCommentRepository.cs
  src/EA.Iws.Domain/NotificationAssessment/INotificationCommentRepository.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/GetImportNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/ImportNotification/GetImportNotificationCommentsUsersHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/DeleteNotificationCommentHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/GetNotificationCommentsHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Notification/GetNotificationCommentsUsersHandlerTests.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/GetImportNotificationCommentsHandler.cs
  src/EA.Iws.RequestHandlers/ImportNotificationAssessment/GetImportNotificationCommentsUsersHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/DeleteNotificationCommentHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/GetNotificationCommentsHandler.cs
  src/EA.Iws.RequestHandlers/NotificationAssessment/GetNotificationCommentsUsersHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/ImportNotificationAssessment/GetImportNotificationComments.cs
  src/EA.Iws.Requests/ImportNotificationAssessment/GetImportNotificationCommentsUsers.cs
  src/EA.Iws.Requests/NotificationAssessment/DeleteNotificationComment.cs
  src/EA.Iws.Requests/NotificationAssessment/GetNotificationComments.cs
  src/EA.Iws.Requests/NotificationAssessment/GetNotificationCommentsUsers.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Comments/Index.cshtml
  src/EA.Iws.Web/Areas/AdminImportAssessment/Controllers/CommentsController.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/ViewModels/Comments/CommentsViewModel.cs
  src/EA.Iws.Web/Areas/AdminImportAssessment/Views/Comments/Index.cshtml
Labels: shipment-notification-comments

#909 Hotfix/internal imports
  src/EA.Iws.RequestHandlers/Admin/Search/SearchExportNotificationsHandler.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModel.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.Designer.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.resx
  src/EA.Iws.Web/Areas/ImportNotification/Views/Shared/EditorTemplates/ContactViewModel.cshtml
Labels: address-book-imports

#911 Revert "Feature/approve fg screen new fields"
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190311-0951-alter-notification-fg-table.sql
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeApprovalTests.cs
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeApproveTests.cs
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeCollectionTests.cs
  src/EA.Iws.Domain/FinancialGuarantee/ApprovalData.cs
  src/EA.Iws.Domain/FinancialGuarantee/FinancialGuarantee.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Admin/FinancialGuarantee/ApproveFinancialGuaranteeHandlerTests.cs
  src/EA.Iws.RequestHandlers/Admin/FinancialGuarantee/ApproveFinancialGuaranteeHandler.cs
  src/EA.Iws.Requests/Admin/FinancialGuarantee/ApproveFinancialGuarantee.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/FinancialGuaranteeDecisionController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/ApproveFinancialGuaranteeViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/FinancialGuaranteeDecisionResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/FinancialGuaranteeDecisionResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/FinancialGuaranteeDecision/Approve.cshtml
Labels: reporting

#913 Revert report amendments
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Finance/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/ImportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/ExportStats/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/Finance/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/ImportStats/Index.cshtml
Labels: reporting

#915 Update producer report
  src/EA.Iws.Database/scripts/Everytime/02-Views/0027-Reports-Producers.sql
Labels: reporting

#924 Producer report update (plus other reports)
  src/EA.Iws.Core/Reports/TextFieldOperator.cs
  src/EA.Iws.Core/Reports/TextFilterHelper.cs
  src/EA.Iws.DataAccess/Repositories/Reports/FreedomOfInformationRepository.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ProducerRepository.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ShipmentsRepository.cs
Labels: reporting

#927 Text updates
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.Designer.cs
  src/EA.Iws.Web/Areas/ImportNotification/ViewModels/Shared/ContactViewModelResources.resx
  src/EA.Iws.Web/Areas/Reports/Views/FreedomOfInformation/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/FreedomOfInformation/IndexResources.resx
Labels: address-book-imports, reporting

#932 Fix notification status for shipments report.
  src/EA.Iws.Database/scripts/Everytime/02-Views/0026-Reports-Shipments.sql
Labels: reporting

#933 Use correct lookup table for import notifications status
  src/EA.Iws.Database/scripts/Everytime/02-Views/0026-Reports-Shipments.sql
Labels: reporting

#937 Use correct look up notification status for imports in foi report.
  src/EA.Iws.Database/scripts/Everytime/02-Views/0022-Reports-FreedomOfInformation.sql
Labels: reporting

#938 Retrieve notification type when invalid model on post.
  src/EA.Iws.Web/Areas/ImportNotification/Controllers/FacilityController.cs
Labels: address-book-imports

#941 Switched the order around on the overiew screens
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Overview/Sections/_CustomsOffice.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/Home/OverviewSections/_CustomsOffice.cshtml
Labels: brexit

#942 Swapped the entry and exit order on the annex in the word doc template
  src/EA.Iws.Api/Documents/NotificationMergeTemplate.docx
Labels: brexit

#912 Feature/financial guarantees report
  src/EA.Iws.Core/Admin/Reports/FinancialGuaranteesData.cs
  src/EA.Iws.DataAccess/Repositories/Reports/FinancialGuaranteesRepository.cs
  src/EA.Iws.Database/EA.Iws.Database.csproj
  src/EA.Iws.Database/scripts/Everytime/02-Views/0025-Reports-BlanketBonds.sql
  src/EA.Iws.Database/scripts/Update/0005-Beta/Sprint7/20190311-0951-alter-notification-fg-table.sql
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeApprovalTests.cs
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeApproveTests.cs
  src/EA.Iws.Domain.Tests.Unit/FinancialGuarantee/FinancialGuaranteeCollectionTests.cs
  src/EA.Iws.Domain/FinancialGuarantee/ApprovalData.cs
  src/EA.Iws.Domain/FinancialGuarantee/FinancialGuarantee.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Admin/FinancialGuarantee/ApproveFinancialGuaranteeHandlerTests.cs
  src/EA.Iws.RequestHandlers/Admin/FinancialGuarantee/ApproveFinancialGuaranteeHandler.cs
  src/EA.Iws.Requests/Admin/FinancialGuarantee/ApproveFinancialGuarantee.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/FinancialGuaranteeDecisionController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/ApproveFinancialGuaranteeViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/FinancialGuaranteeDecisionResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/FinancialGuaranteeDecision/FinancialGuaranteeDecisionResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/FinancialGuaranteeDecision/Approve.cshtml
  src/EA.Iws.Web/Areas/Reports/Controllers/FinancialGuaranteesController.cs
  src/EA.Iws.Web/Areas/Reports/Views/FinancialGuarantees/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/FinancialGuarantees/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/FinancialGuarantees/IndexResources.resx
Labels: reporting

#948 Amendments to export stats, import stats and finance reports.
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Finance/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/ImportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/ExportStats/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/Finance/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/ImportStats/Index.cshtml
Labels: reporting

#950 Ensure validation result is assigned against the correct property name.
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportStats/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/Finance/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/ImportStats/IndexViewModel.cs
Labels: reporting

#947 Added in extra inputs to the report
  src/EA.Iws.Core/EA.Iws.Core.csproj
  src/EA.Iws.Core/Reports/OrganisationFilterOptions.cs
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportMovements/IndexViewModel.cs
  src/EA.Iws.Web/Areas/Reports/Views/ExportMovements/Index.cshtml
  src/EA.Iws.Web/Areas/Reports/Views/ExportMovements/IndexResources.Designer.cs
  src/EA.Iws.Web/Areas/Reports/Views/ExportMovements/IndexResources.resx
Labels: reporting

#953 Give readonly users access to comments section
  src/EA.Iws.RequestHandlers/Authorization/InMemoryAuthorizationManager.cs
Labels: shipment-notification-comments

#958 Changed active loads output to be Y or N
  src/EA.Iws.Core/Admin/Reports/FinancialGuaranteesData.cs
  src/EA.Iws.Database/scripts/Everytime/02-Views/0025-Reports-BlanketBonds.sql
Labels: reporting

#959 Hotfix/custom office text update
  src/EA.Iws.Web/Areas/NotificationApplication/Views/EntryCustomsOffice/_EntryCustomsOfficeGuidance.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/ExitCustomsOffice/_ExitCustomsOfficeGuidance.cshtml
Labels: brexit

#961 Changed wording on the entry and exit customs screen guidance. Fixed …
  src/EA.Iws.Web/Areas/NotificationApplication/Controllers/EntryCustomsOfficeController.cs
  src/EA.Iws.Web/Areas/NotificationApplication/Controllers/ExitCustomsOfficeController.cs
  src/EA.Iws.Web/Areas/NotificationApplication/Views/EntryCustomsOffice/_EntryCustomsOfficeGuidance.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/Views/ExitCustomsOffice/_ExitCustomsOfficeGuidance.cshtml
Labels: brexit

#963 Feature/export movement report upgrade run
  src/EA.Iws.Core/Reports/OrganisationFilterOptions.cs
  src/EA.Iws.DataAccess/Repositories/Reports/ExportMovementsRepository.cs
  src/EA.Iws.Domain/Reports/IExportMovementsRepository.cs
  src/EA.Iws.RequestHandlers/Admin/Reports/GetExportMovementsReportHandler.cs
  src/EA.Iws.Requests/Admin/Reports/GetExportMovementsReport.cs
  src/EA.Iws.Web/Areas/Reports/Controllers/ExportMovementsController.cs
Labels: reporting

#964 Updated third column title for export movement document report.
  src/EA.Iws.Core/Admin/Reports/ExportMovementsData.cs
Labels: reporting

#962 Fixed issue where model validation not happening for org type unless …
  src/EA.Iws.Web/Areas/Reports/ViewModels/ExportMovements/IndexViewModel.cs
Labels: reporting

#966 Fixed bug with export documents not being included in org filter
  src/EA.Iws.DataAccess/Repositories/Reports/ExportMovementsRepository.cs
Labels: reporting

#968 Feature/internal change recover disposal code
  src/EA.Iws.Core/Authorization/Permissions/ExportNotificationPermissions.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/Admin/NotificationAssessment/SetOperationCodesHandlerTests.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers/Authorization/InMemoryAuthorizationManager.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/NotificationAssessment/SetOperationCodesHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/NotificationAssessment/SetOperationCodes.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/OperationCodesController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/OverviewController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/OperationCodes/OperationCodesViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/Edit.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/EditResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/EditResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Overview/Sections/_OperationCodes.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/ViewModels/NotificationApplication/RecoveryOperationViewModel.cs
  src/EA.Iws.Web/EA.Iws.Web.csproj
Labels: continuous-improvement

#967 Export notifications change Y codes
  src/EA.Iws.Core/Authorization/Permissions/ExportNotificationPermissions.cs
  src/EA.Iws.RequestHandlers.Tests.Unit/EA.Iws.RequestHandlers.Tests.Unit.csproj
  src/EA.Iws.RequestHandlers.Tests.Unit/WasteCodes/EditYCodesHandlerTests.cs
  src/EA.Iws.RequestHandlers/Authorization/InMemoryAuthorizationManager.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/WasteCodes/EditYCodesHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/WasteCodes/EditYCodes.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/OverviewController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/YCodeController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/YCode/EditYCodeViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Overview/Sections/_YCodes.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Shared/EditorTemplates/EnterWasteCodesViewModel.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/YCode/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/YCode/YCodeResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/YCode/YCodeResources.resx
  src/EA.Iws.Web/Areas/NotificationApplication/ViewModels/NotificationApplication/WasteCodeOverviewViewModel.cs
  src/EA.Iws.Web/EA.Iws.Web.csproj
  src/EA.Iws.Web/Infrastructure/Constants.cs
  src/EA.Iws.Web/Mappings/NotificationAssessment/EditYCodeMap.cs
Labels: continuous-improvement

#969 Edit EWC Code
  src/EA.Iws.Core/Authorization/Permissions/ExportNotificationPermissions.cs
  src/EA.Iws.RequestHandlers/Authorization/InMemoryAuthorizationManager.cs
  src/EA.Iws.RequestHandlers/EA.Iws.RequestHandlers.csproj
  src/EA.Iws.RequestHandlers/NotificationAssessment/UpdateEwcCodeHandler.cs
  src/EA.Iws.Requests/EA.Iws.Requests.csproj
  src/EA.Iws.Requests/NotificationAssessment/UpdateEwcCode.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/EditEwcCodeController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Controllers/OverviewController.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/EditEwcCode/EditEwcCodeViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/ViewModels/EditEwcCode/EditEwcEnterCodesViewModel.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/EditEwcCode/EditEwcCodeResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/EditEwcCode/EditEwcCodeResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/EditEwcCode/Index.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Overview/Sections/_EwcCodes.cshtml
  src/EA.Iws.Web/Areas/NotificationApplication/ViewModels/NotificationApplication/WasteCodeOverviewViewModel.cs
  src/EA.Iws.Web/EA.Iws.Web.csproj
  src/EA.Iws.Web/Mappings/AdminExportAssessment/EditEwcMap.cs
Labels: continuous-improvement

#970 Changed wording
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/Edit.cshtml
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/EditResources.Designer.cs
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/OperationCodes/EditResources.resx
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/Overview/Sections/_OperationCodes.cshtml
Labels: continuous-improvement

#971 Add missing red border for validation message.
  src/EA.Iws.Web/Areas/Reports/Views/ExportMovements/Index.cshtml
Labels: reporting

#977 FG approve screen - input attributes for number fields
  src/EA.Iws.Web/Areas/AdminExportAssessment/Views/FinancialGuaranteeDecision/Approve.cshtml
Labels: reporting
